### ISSUE TITLE
GL/glx.h: No such file or directory (Linux) (plus other missing files)

### ISSUE THREAD

**Issue by lividhen** [VDavid003/sm64-port-android-base#33]
When src/pc/gfx/gfx_glx.c tries to call GL/glx.h, the build fails because glx.h does not exist. All the steps (Linux build) went fine until the **Compile Natively** step. Also, the compile for android thing does not extract resources from the ROM, i don't know if that is intentional or not... Is there a way to fix this? Nobody else seems to have this issue. I am running Pop!_OS 20.04. Am I doing something wrong?

I ran make again and now it is complaining about more missing files.
A bunch of things need SDL2/SDL.h
src/pc/audio/audio_pulse.c needs pulse/pulseaudio.h
src/[c/audio/audio_alsa.c needs alsa/asoundlib.h

I am in app/jni/src when running make. 
I did run getSDL.sh in the root of the project, and also the one in app/jni/src.

**Comment by TechdudeGames** [comment]
So `GL/gfx.h` and `SDL2/SDL.h` and those other missing files you will have to add to you system. On pop you will have to run `sudo apt install build-essential git python3 libglew-dev libsdl2-dev` to grab all of the dependencies. The android build can't extract the assets as of yet, which is why the native port has to be built so that it can extract them for us.

**Comment by lividhen** [comment]
Thanks, this fixed it!
