### ISSUE TITLE
Add Termux building support

### ISSUE THREAD

**Issue by jword2** [VDavid003/sm64-port-android-base#5]

**Comment by jword2** [comment]
It didn't work

**Comment by jword2** [comment]
Plz help

**Comment by VDavid003** [comment]
Can't help without any description of the problem.
Can you tell me:
What platform you tried to build this on?
What branch did you use?
Did it succeed?
If not, what happened? Can you show terminal/command prompt output?
If yes, what is the problem? Can you provide logcat if it crashed?

**Comment by jword2** [comment]
When I tried app termux didn't work

**Comment by jword2** [comment]
And send me an apk or not I need to test it

**Comment by VDavid003** [comment]
Termux building support will come later. I just made the neccessary modifications to the makefile, I'll close this issue when it's done.
Also I'm renaming the issue to be more descriptive!

**Comment by VDavid003** [comment]
Initial "Alpha" of building on termux available here: https://github.com/VDavid003/sm64-port-android/tree/termux_build
There's no standalone builder with UI yet but it will happen (also, non-vanilla branches).
Since the issue is about building on termux, I'll close it since it's possible now, though only vanilla version yet.
