### ISSUE TITLE
Poor performance on Oneplus 8 Pro

### ISSUE THREAD

**Issue by MaciekBaron** [VDavid003/sm64-port-android-base#56]
For some weird reason when building and running the game on my Oneplys 8 Pro (Snapdragon 865), the game runs very slowly. Could it be because of the resolution of the phone? Is there anything I could try doing?

**Comment by rbeesley** [comment]
I just built it in Termux for the OnePlus 8 Pro. It isn't the resolution, it is the 120Hz refresh rate. I feel like this is something introduced in the last year because when this port first came out I tried it on the same device and didn't remember any problems at 120Hz. Switching between FHD+ and QHD+ didn't change anything, but at 60Hz it worked fine at both resolutions.

**Comment by MaciekBaron** [comment]
Thanks, you're right - when I switched to 60hz, it performed normally. I'll close this issue and create a specific one.
